name: docs
on:
  push:
    branches:
      - dev

jobs:
  build-docs:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - run: npm ci
      - run: npm run docs:build
        env:
          VITEPRESS_HOST_WITH_BASE: https://nandenjin.github.io/obakesan
          VITEPRESS_BASE: /obakesan
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist

  deploy-docs:
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-slim
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
